apiVersion: v1
kind: Service

metadata:
  name: pcode-markdown2-service
  namespace: pcode
  labels:
    app: pcode-markdown2

spec:
  selector:
    app: pcode-markdown2
  type: NodePort
  clusterIP: 10.152.183.80
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
